const prefixes =
{
    rdf: `<http://www.w3.org/1999/02/22-rdf-syntax-ns#>`,
    rdfs: `<http://www.w3.org/2000/01/rdf-schema#>`,
    sesame: `<http://www.openrdf.org/schema/sesame#>`,
    owl: `<http://www.w3.org/2002/07/owl#>`,
    xsd: `<http://www.w3.org/2001/XMLSchema#>`,
    fn: `<http://www.w3.org/2005/xpath-functions#>`,
    foaf: `<http://xmlns.com/foaf/0.1/>`,
    dc: `<http://purl.org/dc/elements/1.1/>`,
    hint: `<http://www.bigdata.com/queryHints#>`,
    bd: `<http://www.bigdata.com/rdf#>`,
    bds: `<http://www.bigdata.com/rdf/search#>`,
    psn: `<http://www.wikidata.org/prop/statement/value-normalized/>`,
    pqn: `<http://www.wikidata.org/prop/qualifier/value-normalized/>`,
    prn: `<http://www.wikidata.org/prop/reference/value-normalized/>`,
    mwapi: `<https://www.mediawiki.org/ontology#API/>`,
    gas: `<http://www.bigdata.com/rdf/gas#>`,
    wdt: `<http://www.wikidata.org/prop/direct/>`,
    wdtn: `<http://www.wikidata.org/prop/direct-normalized/>`,
    psv: `<http://www.wikidata.org/prop/statement/value/>`,
    ps: `<http://www.wikidata.org/prop/statement/>`,
    pqv: `<http://www.wikidata.org/prop/qualifier/value/>`,
    pq: `<http://www.wikidata.org/prop/qualifier/>`,
    prv: `<http://www.wikidata.org/prop/reference/value/>`,
    pr: `<http://www.wikidata.org/prop/reference/>`,
    wdno: `<http://www.wikidata.org/prop/novalue/>`,
    p: `<http://www.wikidata.org/prop/>`,
    wikibase: `<http://wikiba.se/ontology#>`,
    wd: `<http://www.wikidata.org/entity/>`,
    wds: `<http://www.wikidata.org/entity/statement/>`,
    wdv: `<http://www.wikidata.org/value/>`,
    wdref: `<http://www.wikidata.org/reference/>`,
    wdata: `<http://www.wikidata.org/wiki/Special:EntityData/>`,
    schema: `<http://schema.org/>`,
    prov: `<http://www.w3.org/ns/prov#>`,
    skos: `<http://www.w3.org/2004/02/skos/core#>`,
    geo: `<http://www.opengis.net/ont/geosparql#>`,
    geof: `<http://www.opengis.net/def/geosparql/function/>`,
    mediawiki: `<https://www.mediawiki.org/ontology#>`,
    ontolex: `<http://www.w3.org/ns/lemon/ontolex#>`,
    dct: `<http://purl.org/dc/terms/>`,
}

module.exports = {
    prefixes,
}