SELECT ?game ?gameLabel ?platform ?platformLabel ?developer ?developerLabel ?publisher ?publisherLabel ?genre ?genreLabel ?game_mode ?game_modeLabel ?official_website ?official_websiteLabel ?publication_date ?publication_dateLabel ?part_of_the_series ?part_of_the_seriesLabel ?software_engine ?software_engineLabel ?pegi_rating ?pegi_ratingLabel ?review_score ?review_scoreLabel ?title ?titleLabel ?country_of_origin ?country_of_originLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  ?game wdt:P31 wd:Q7889.
  OPTIONAL { ?game wdt:P400 ?platform }
  OPTIONAL { ?game wdt:P178 ?developer}
  OPTIONAL { ?game wdt:P123 ?publisher. }
  OPTIONAL { ?game wdt:P136 ?genre. }
  OPTIONAL { ?game wdt:P404 ?game_mode. }
  OPTIONAL { ?game wdt:P856 ?official_website. }
  OPTIONAL { ?game wdt:P577 ?publication_date. }
  OPTIONAL { ?game wdt:P179 ?part_of_the_series. }
  OPTIONAL { ?game wdt:P408 ?software_engine. }
  OPTIONAL { ?game wdt:P908 ?pegi_rating. }
  OPTIONAL { ?game wdt:P444 ?review_score. }
  OPTIONAL { ?game wdt:P1476 ?title. }
  OPTIONAL { ?game wdt:P495 ?country_of_origin. }
}
limit 5